/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;

import java.io.FileNotFoundException;

import supportbank.Bank.Bank;
import supportbank.Logging.Logging;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        Bank bank = new Bank();
        Logging logger = new Logging();
        logger.programStart();

        // System.out.println("Enter command:" + "ListAll OR List");
        // Scanner scanner = new Scanner(System.in);
        // String userPrompt = scanner.nextLine();
        // if (userPrompt.equals("ListAll")) {
        //     bank.listAllAccountAndBalance();
        // } else if (userPrompt.equals("List")) {
        //     System.out.println("Enter account holder name:");
        //     String name = scanner.nextLine();
        //     bank.listPerson(name);
        // }
        // scanner.close();
        
    }
}
