/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package supportbank;

import java.io.FileNotFoundException;
import java.util.Scanner;

import supportbank.Bank.Bank;
import supportbank.Logging.Logging;
import supportbank.Operation.ListAllAccount;
import supportbank.Operation.ListPersonTransaction;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        Bank bank = new Bank();
        Logging logger = new Logging();
        logger.programStart();

        System.out.println("Enter command:" + "ListAll OR List, or enter Exit");
        Scanner scanner = new Scanner(System.in);
        while (true) {
            String userPrompt = scanner.nextLine();
            if (userPrompt.equals("ListAll")) {
                ListAllAccount accountAndBalance = new ListAllAccount();
                bank.executeAll(accountAndBalance);

            } else if (userPrompt.equals("List")) {
                System.out.println("Enter account holder name:");
                String name = scanner.nextLine();
                ListPersonTransaction personTransaction = new ListPersonTransaction(name);
                bank.executeAll(personTransaction);
            } else if (userPrompt.equals("Exit")) {
                break;
            } else {
                System.out.println("Oops! Looks like you entered an incorrect prompt. Please try again!");
            }
        }
        scanner.close();

    }
}
